version: '3'
services:
  client:
    build: client
    ports:
      - "8080:3000"
    restart: always
    env_file:
      - client/.env

  server:
    build: server
    ports:
      - "8081:8081"
    networks:
      - db
    depends_on:
      - mongo
    restart: always
    environment:
      - MONGOURI=mongodb://mongo:27017/${MONGO_DBNAME}
    env_file:
      - client/.env

  mongo:
    image: mongo
    networks:
      - db
    volumes:
      - db-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DBNAME}
    env_file:
      - .env

networks:
  db:

volumes:
  db-data:
