version: '3'
services:
  client:
    build: client
    ports:
      - "8080:3000"
    restart: always

  server:
    build: server
    ports:
      - "8081:3000"
    environment:
      - MONGOURI=mongodb://mongo:27017/${MONGO_DBNAME}
    networks:
      - db
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DBNAME}
    networks:
      - db
    volumes:
      - db-data:/data/db
    restart: always

networks:
  db:

volumes:
  db-data:
